remove:
  - anaconda
  - anaconda-core
  - anaconda-gui
  - anaconda-widgets
  - anaconda-live
  - anaconda-tui
  - anaconda-install-env-deps
  - libreport-anaconda
  - calamares
  - calamares-plasma
  - livesys-scripts
  - livesys
  - grub2
  - grub2-tools
  - grub2-efi-x64
